<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CFA" nsURI="http://CFA/1.0" nsPrefix="CFA">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="MG" value="MG.ecore#/"/>
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="CFN">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" upperBound="-1"
        eType="#//GlobalState" containment="true" eOpposite="#//GlobalState/cfn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hunks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bugFix" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weightFactor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalWeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalBugWeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageWeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageBugWeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fixes" upperBound="-1"
        eType="#//State" eOpposite="#//State/causes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="causes" upperBound="-1"
        eType="#//State" eOpposite="#//State/fixes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalState" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cfn" eType="#//CFN" eOpposite="#//CFN/globalStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifactStates" upperBound="-1"
        eType="#//ArtifactState" containment="true" eOpposite="#//ArtifactState/globalState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="revision" eType="ecore:EClass MG.ecore#//Revision"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactState" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalState" eType="#//GlobalState"
        eOpposite="#//GlobalState/artifactStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="file" eType="ecore:EClass MG.ecore#//File"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="ecore:EClass MG.ecore#//Action"/>
  </eClassifiers>
</ecore:EPackage>
